### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kodeine** [mixmaxhq/eb-disable-npm#4]
```
/node_modules/eb-disable-npm
> install-files source

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)

```

**Comment by wearhere** [comment]
How did you reproduce this? Can't tell from the trace

**Comment by danbovey** [comment]
I got this error as well after installing `eb-fix-npm` or `eb-disable-npm`.

```
+ npm install

> eb-disable-npm@1.0.0 install <project>/node_modules/eb-disable-npm
> install-files source

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at installFiles (<project>/node_modules/install-files/src/index.js:63:19)
    at Object.<anonymous> (<project>/node_modules/install-files/bin/install-files.js:16:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by wearhere** [comment]
What's your OS and Node version?

**Comment by danbovey** [comment]
```
ubuntu@ip:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
ubuntu@ip:~$ node -v
v6.11.0
ubuntu@ip:~$ npm -v
5.6.0
```

I've seen a lot of comments around these problems with people saying they've moved to docker instead of messing about with ebextensions so that's what I've done too. :100:

**Comment by wearhere** [comment]
> I've seen a lot of comments around these problems with people saying they've moved to docker instead of messing about with ebextensions so that's what I've done too.

Oh interesting. Using AWS ECS? Or Docker on Elastic Beanstalk?

Re: the trace, what's weird is that

>     at installFiles (<project>/node_modules/install-files/src/index.js:63:19)

Corresponds to a [blank line](https://github.com/mixmaxhq/install-files/blob/1c6301a7498924f8f2881812e97b7a8588bb5bda/src/index.js#L63) in `install-files`. Can you do `npm ls install-files` to see what version of `install-files` your install of `eb-disable-npm` is using? Over the course of [1.x](https://github.com/mixmaxhq/eb-disable-npm/blob/e756d705d7b323bec40c9ff70dac23746e6d1b22/package.json#L29) we've made some fixes to path lookups—perhaps this would be fixed by forcing `eb-disable-npm` to upgrade to the latest 1.x.

**Comment by danbovey** [comment]
[Docker on Elastic Beanstalk](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.html)

---

If I run `cd install-files && cat package.json` quickly before it crashes it says it has downloaded version `1.1.4` of `install-files`.
